### ISSUE TITLE
Cannot link for simulator after using JSONTools

### ISSUE THREAD

**Issue by wewei** [grgcombs/JSONTools#4]
### CocoaPods version:
0.35.0

### XCode version:
6.1

### Error:
ld: warning: ignoring file /Users/wewei/Library/Developer/Xcode/DerivedData/Mathematician-gurehmzhckidwfajxlzdouehxzhg/Build/Products/Debug-iphonesimulator/libPods-Mathematician-Mathematician.a, file was built for archive which is not the architecture being linked (i386): /Users/wewei/Library/Developer/Xcode/DerivedData/Mathematician-gurehmzhckidwfajxlzdouehxzhg/Build/Products/Debug-iphonesimulator/libPods-Mathematician-Mathematician.a
ld: warning: ignoring file /Users/wewei/Library/Developer/Xcode/DerivedData/Mathematician-gurehmzhckidwfajxlzdouehxzhg/Build/Products/Debug-iphonesimulator/libPods-Mathematician-AFNetworking.a, file was built for archive which is not the architecture being linked (i386): /Users/wewei/Library/Developer/Xcode/DerivedData/Mathematician-gurehmzhckidwfajxlzdouehxzhg/Build/Products/Debug-iphonesimulator/libPods-Mathematician-AFNetworking.a
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_PhDMathematician", referenced from:
      objc-class-ref in PhDViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Root cause:
JSONTools generates "ONLY_ACTIVE_ARCH=No" for all targets, but it's conflict with pods' default value, 'YES' for debug while 'NO' for release.

### Suggestion:
Remove the  the "ONLY_ACTIVE_ARCH"?

**Comment by grgcombs** [comment]
Yeah that's reasonable. I think I need to find a CocoaPods setting that reenables it for all pods when building a fat static library in a separate project of mine. However, I think the new clang module support in 0.36.beta1 makes all of that moot -- everything becomes a fat module framework.

**Comment by cvasilak** [comment]
Hi @grgcombs, thank you for your work on this library!

I am currently using it as a dependency in a Swift library I am writing and having the same issue as user @wewei. I would like to ask what is your plan regarding the override of the "'ONLY_ACTIVE_ARCH'" setting? Is it planned to be removed? Have you managed to find a workaround with cocoapods?

Thanks in advance

**Comment by grgcombs** [comment]
Try v1.0.5 with cc7b48f7ecbbbe0471f7f5883bc6c472d114e77c -- I pulled out the ONLY_ACTIVE_ARCH override.  I'm having some issues with Cocoapods on my end, but from the Travis CI results, it all looks good now.
